# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GuildTotalActivityPoints.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'GuildTotalActivityPoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGuildTotalActivityPoints.proto\",\n\x0bLeaderboard\x12\x1d\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0c.RankWrapper\"M\n\x0bRankWrapper\x12\x0c\n\x04rank\x18\x04 \x01(\r\x12\x10\n\x08guild_id\x18\x01 \x01(\x04\x12\x1e\n\x07profile\x18\x03 \x01(\x0b\x32\r.GuildProfile\"\x9b\x03\n\x0cGuildProfile\x12&\n\x07\x64\x65tails\x18\x01 \x01(\x0b\x32\x15.GuildProfile.Details\x1a\xe2\x02\n\x07\x44\x65tails\x12\x10\n\x08guild_id\x18\x01 \x01(\x04\x12\x12\n\nguild_name\x18\x02 \x01(\t\x12\x12\n\nleader_uid\x18\x04 \x01(\x04\x12\x13\n\x0bguild_level\x18\x05 \x01(\r\x12\x17\n\x0fmaximum_members\x18\x06 \x01(\r\x12\x15\n\rtotal_members\x18\x07 \x01(\r\x12\x1e\n\x16minimum_level_required\x18\x08 \x01(\r\x12\x15\n\rauto_approval\x18\t \x01(\r\x12\x0e\n\x06slogan\x18\x0c \x01(\t\x12\x0e\n\x06region\x18\r \x01(\t\x12 \n\x18minimum_br_rank_required\x18\x16 \x01(\r\x12 \n\x18minimum_cs_rank_required\x18# \x01(\r\x12\x1d\n\x15total_activity_points\x18$ \x01(\x04\x12\x1e\n\x16weekly_activity_points\x18% \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GuildTotalActivityPoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEADERBOARD']._serialized_start=34
  _globals['_LEADERBOARD']._serialized_end=78
  _globals['_RANKWRAPPER']._serialized_start=80
  _globals['_RANKWRAPPER']._serialized_end=157
  _globals['_GUILDPROFILE']._serialized_start=160
  _globals['_GUILDPROFILE']._serialized_end=571
  _globals['_GUILDPROFILE_DETAILS']._serialized_start=217
  _globals['_GUILDPROFILE_DETAILS']._serialized_end=571
# @@protoc_insertion_point(module_scope)
